import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import App from './App'

describe('sitio de detallado automotriz', () => {
  it('presenta los servicios y sus precios', () => {
    render(<App />)

    expect(screen.getByRole('heading', { name: 'Detallado interior' })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Detallado exterior' })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Protección cerámica en carrocería' })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Restauración de focos' })).toBeInTheDocument()
    expect(screen.getByText('₡50.000')).toBeInTheDocument()
    expect(screen.getByText(/precios están sujetos a cambios/i)).toBeInTheDocument()
    expect(screen.getAllByRole('img', { name: 'AutoEstudioCR Detailing' })).toHaveLength(2)
  })

  it('muestra SINPE, solicita comprobante y mantiene tarjeta en pausa', async () => {
    const user = userEvent.setup()
    render(<App />)

    await user.click(screen.getAllByRole('button', { name: /reservar mi cita/i })[0])
    const dialog = screen.getByRole('dialog')
    expect(within(dialog).getByText('+506 0000-0000')).toBeInTheDocument()
    expect(within(dialog).getByText('Seleccionar archivo')).toBeInTheDocument()
    expect(within(dialog).getByLabelText(/comprobante sinpe/i)).toBeRequired()
    expect(within(dialog).getByRole('radio', { name: /tarjeta/i })).toBeDisabled()
    const receipt = new File(['receipt'], 'comprobante.pdf', { type: 'application/pdf' })
    await user.upload(within(dialog).getByLabelText(/comprobante sinpe/i), receipt)
    await waitFor(() => expect(within(dialog).getByText(/comprobante\.pdf/)).toBeInTheDocument())
  })

  it('presenta errores de comprobante en lenguaje útil para el cliente', async () => {
    fetch.mockResolvedValueOnce({ ok: false, json: async () => ({ error: 'Sin sesión' }) }).mockResolvedValueOnce({ ok: false, json: async () => ({ error: 'No pudimos adjuntar el comprobante. Verifica que sea una imagen o PDF menor de 5 MB e intenta nuevamente; también puedes elegir pago en efectivo.' }) })
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getAllByRole('button', { name: /reservar mi cita/i })[0])
    const dialog = screen.getByRole('dialog')
    await user.type(within(dialog).getByLabelText(/nombre completo/i), 'Sofía')
    await user.type(within(dialog).getByLabelText(/teléfono/i), '88881234')
    await user.type(within(dialog).getByLabelText(/correo/i), 'sofia@example.com')
    await user.type(within(dialog).getByLabelText(/vehículo/i), 'Nissan Navara')
    await user.type(within(dialog).getByLabelText(/fecha/i), '2030-08-22')
    await user.selectOptions(within(dialog).getByLabelText(/hora/i), '14:00')
    await user.click(within(dialog).getByRole('radio', { name: /efectivo/i }))
    await user.click(within(dialog).getByRole('button', { name: /solicitar reservación/i }))
    expect(within(dialog).getByRole('alert')).toHaveTextContent('No pudimos adjuntar el comprobante')
    expect(within(dialog).getByRole('alert')).not.toHaveTextContent(/Cloud Storage|GCP|diagnóstico administrativo/i)
  })

  it('registra una cita y permite gestionarla desde el panel', async () => {
    const user = userEvent.setup()
    render(<App />)

    await user.click(screen.getAllByRole('button', { name: /reservar mi cita/i })[0])
    const dialog = screen.getByRole('dialog')
    await user.type(within(dialog).getByLabelText(/nombre completo/i), 'Sofía Méndez')
    await user.type(within(dialog).getByLabelText(/teléfono/i), '88881234')
    await user.type(within(dialog).getByLabelText(/correo/i), 'sofia@example.com')
    await user.type(within(dialog).getByLabelText(/vehículo/i), 'Mazda 3 2024')
    await user.type(within(dialog).getByLabelText(/fecha/i), '2030-05-20')
    await user.selectOptions(within(dialog).getByLabelText(/hora/i), '11:00')
    await user.click(within(dialog).getByRole('radio', { name: /efectivo/i }))
    await user.click(within(dialog).getByRole('button', { name: /solicitar reservación/i }))

    expect(within(dialog).getByRole('heading', { name: /gracias, sofía/i })).toBeInTheDocument()
    const storedBookings = JSON.parse(localStorage.getItem('detail-bookings'))
    expect(storedBookings).toHaveLength(1)
    expect(storedBookings[0].cost).toBe(5000)
    expect(fetch).toHaveBeenCalledWith('/api/bookings', expect.objectContaining({ method: 'POST' }))

    await user.click(within(dialog).getByRole('button', { name: 'Listo' }))
    await user.click(screen.getByRole('button', { name: 'Administrar' }))
    const login = screen.getByRole('dialog')
    await user.type(within(login).getByLabelText(/correo/i), 'admin@estudioauto.com')
    await user.type(within(login).getByLabelText(/contraseña/i), 'admin123')
    await user.click(within(login).getByRole('button', { name: 'Ingresar' }))
    const admin = screen.getByText('PANEL DE ADMINISTRACIÓN').closest('section')
    expect(within(admin).getByRole('img', { name: 'Servicios disponibles' })).toBeInTheDocument()
    expect(admin).not.toHaveTextContent(/GCP|Firestore|Cloud Storage/i)
    fireEvent.change(within(admin).getByLabelText('Mes a consultar'), { target: { value: '2030-05' } })
    expect(within(admin).getByText('Sofía Méndez')).toBeInTheDocument()
    expect(within(admin).getByText('Mazda 3 2024')).toBeInTheDocument()
    expect(within(admin).getByRole('link', { name: /whatsapp/i })).toHaveAttribute('href', expect.stringContaining('88881234'))
    await user.click(within(admin).getByRole('button', { name: /ver reserva y gestionar/i }))
    const detail = screen.getByText('DETALLE DE LA RESERVA').closest('section')
    expect(within(detail).getByRole('heading', { name: 'Detallado interior' })).toBeInTheDocument()
    expect(within(detail).getByRole('button', { name: /finalizar/i })).toBeDisabled()
    await user.click(within(detail).getByRole('button', { name: /aprobar/i }))
    expect(fetch).toHaveBeenCalledWith('/api/booking-updates', expect.objectContaining({ method: 'POST' }))
    await user.click(within(detail).getByRole('button', { name: /acabado exterior/i }))
    expect(within(detail).getByAltText('Acabado exterior')).toBeInTheDocument()
    await user.click(within(detail).getByRole('button', { name: /marcar efectivo como pagado/i }))
    expect(within(detail).getByRole('button', { name: /finalizar/i })).toBeEnabled()
    await user.click(within(detail).getByRole('button', { name: 'Cerrar' }))
    expect(within(admin).getByText('Confirmada')).toBeInTheDocument()
  })

  it('muestra el estado vacío del panel cuando no hay citas', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: 'Administrar' }))
    const login = screen.getByRole('dialog')
    await user.type(within(login).getByLabelText(/correo/i), 'admin@estudioauto.com')
    await user.type(within(login).getByLabelText(/contraseña/i), 'admin123')
    await user.click(within(login).getByRole('button', { name: 'Ingresar' }))
    expect(screen.getByText('No hay citas para este mes.')).toBeInTheDocument()
  })

  it('permite crear una cuenta opcional y registrar varios vehículos', async () => {
    const user = userEvent.setup()
    render(<App />)
    expect(screen.getAllByRole('button', { name: /reservar mi cita/i })[0]).toBeEnabled()
    await user.click(screen.getByRole('button', { name: 'Mi cuenta' }))
    const access = screen.getByRole('dialog')
    await user.click(within(access).getByRole('button', { name: 'Registrarme' }))
    await user.type(within(access).getByLabelText(/nombre completo/i), 'Ana López')
    await user.type(within(access).getByLabelText(/teléfono/i), '88889999')
    await user.type(within(access).getByLabelText(/correo/i), 'ana@example.com')
    await user.type(within(access).getByLabelText(/contraseña/i), 'secreto1')
    await user.click(within(access).getByRole('button', { name: 'Crear cuenta' }))
    expect(fetch).toHaveBeenCalledWith('/api/auth/register', expect.objectContaining({ method: 'POST' }))
    expect(localStorage.getItem('detail-accounts')).toBeNull()
    await user.click(await screen.findByRole('button', { name: 'Hola, Ana' }))
    const portal = screen.getByRole('dialog')
    await user.type(within(portal).getByLabelText('Marca'), 'Toyota')
    await user.type(within(portal).getByLabelText('Modelo'), 'RAV4')
    await user.type(within(portal).getByLabelText('Año'), '2023')
    await user.click(within(portal).getByRole('button', { name: /agregar vehículo/i }))
    expect(fetch).toHaveBeenCalledWith('/api/vehicles', expect.objectContaining({ method: 'POST' }))
    expect(within(portal).getByText('Toyota RAV4')).toBeInTheDocument()
  })

  it('impide reservar una fecha bloqueada por administración', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: 'Administrar' }))
    let dialog = screen.getByRole('dialog')
    await user.type(within(dialog).getByLabelText(/correo/i), 'admin@estudioauto.com')
    await user.type(within(dialog).getByLabelText(/contraseña/i), 'admin123')
    await user.click(within(dialog).getByRole('button', { name: 'Ingresar' }))
    dialog = screen.getByRole('dialog')
    fireEvent.change(within(dialog).getByLabelText('Fecha a bloquear'), { target: { value: '2030-06-15' } })
    await user.click(within(dialog).getByRole('button', { name: 'Bloquear' }))
    await user.click(within(dialog).getByRole('button', { name: 'Cerrar' }))
    await user.click(screen.getAllByRole('button', { name: /reservar mi cita/i })[0])
    dialog = screen.getByRole('dialog')
    fireEvent.change(within(dialog).getByLabelText('Fecha'), { target: { value: '2030-06-15' } })
    expect(within(dialog).getByText('Esta fecha no está disponible.')).toBeInTheDocument()
    expect(within(dialog).getByRole('button', { name: /solicitar reservación/i })).toBeDisabled()
  })

  it('permite al cliente abrir una cita histórica y ver sus evidencias', async () => {
    const historical = { id: 2, name: 'Ana López', email: 'ana@example.com', phone: '88889999', vehicle: 'Toyota RAV4', service: 'Signature', date: '2025-02-10', time: '09:00', cost: 60000, status: 'Completada', workDone: 'Descontaminación y cera premium.', evidence: [{ id: 3, type: 'image', url: 'https://example.com/final.jpg', label: 'Resultado final' }] }
    fetch.mockResolvedValueOnce({ ok: true, json: async () => ({ account: { id: 'customer-test', name: 'Ana López', email: 'ana@example.com', phone: '88889999', role: 'customer', cars: [] }, bookings: [historical] }) })
    const user = userEvent.setup()
    render(<App />)
    await user.click(await screen.findByRole('button', { name: 'Hola, Ana' }))
    const portal = screen.getByRole('dialog')
    await user.click(within(portal).getByRole('button', { name: /abrir detalle de signature/i }))
    expect(screen.getByText('Descontaminación y cera premium.')).toBeInTheDocument()
    expect(screen.getByAltText('Resultado final')).toBeInTheDocument()
  })
})
